server:
  port: 8090

spring:
  application:
    name: spring-data-enverse

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_data_enverse_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  main:
#    allow-bean-definition-overriding: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true