server:
  port: 8090

spring:
  application:
    name: spring-data-jpa-audit

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_data_jpa_audit_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true